name: Release

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch: {}

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Test
        run: mvn -B clean test
      - name: Upload Surefire reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**

  build:
    name: Package JAR
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Validate tag matches pom.xml (when tag push)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          POM_VER=$(mvn -q -Dexec.executable=echo \
            -Dexec.args='${project.version}' --non-recursive \
            org.codehaus.mojo:exec-maven-plugin:3.1.0:exec)
          [ "$TAG" = "$POM_VER" ] || { echo "Tag $TAG != pom $POM_VER"; exit 1; }
      - name: Package (skip tests)
        run: mvn -B -DskipTests package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: keycloak-krb-probe
          path: target/keycloak-krb-probe.jar

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: keycloak-krb-probe
          path: dist
      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: dist/keycloak-krb-probe.jar

